# Tipos de datos en numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# para ver el tipo de datos del array

In [3]:
arr.dtype

dtype('int64')

#creamos un array y le pasamos el tipo de dato

In [4]:
arr_float = np.array([1,2,3,4,5,6,7,8,9], dtype='float64')
arr_float

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
type(arr_float)

numpy.ndarray

In [6]:
arr_float.dtype

dtype('float64')

# CONVERTIR TIPOS DE DATOS

In [7]:
arr = np.array([1,0,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool

array([ True, False,  True,  True])

In [8]:
arr.dtype

dtype('int64')

In [10]:
arr_str = arr.astype(np.bytes_)
arr_str

array([b'1', b'0', b'3', b'4'], dtype='|S21')