# IMPORTAMOS PYTORCH

In [2]:
import torch
torch.__version__

'2.9.0+cu126'

# TENSORES

In [3]:
array = [1,2,3]
type(array)

list

In [5]:
escalar = torch.randn(1)
print(escalar)
print(type(escalar))

tensor([-0.2541])
<class 'torch.Tensor'>


In [4]:
vector = torch.zeros(1,10)
vector

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
type(vector)

torch.Tensor

# CALCULO DE GRADIENTE

# CON ARRAY DE NUMPY

In [7]:
import numpy as np

In [8]:
x_np = np.array([1.0, 2.0, 3.0])
y_np = x_np ** 2

print("Resultado NumPy:", y_np)

Resultado NumPy: [1. 4. 9.]


## CON TENSORES DE PYTORCH

In [9]:
x_torch = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y_torch = x_torch ** 2

# Backpropagation
y_torch.sum().backward()

print("Resultado PyTorch:", y_torch)
print("Gradientes:", x_torch.grad)

Resultado PyTorch: tensor([1., 4., 9.], grad_fn=<PowBackward0>)
Gradientes: tensor([2., 4., 6.])


# USO DE GPU

In [10]:
# PyTorch puede usar GPU si está disponible
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_gpu = torch.tensor([1, 2, 3]).to(device)

print("PyTorch device:", tensor_gpu.device)

PyTorch device: cuda:0


# CONVIRTIENDO UN ARRAY DE NUMPY A TENSOR DE PYTORCH

In [11]:
np_array = np.array([1.0, 2.0, 3.0])
tensor_from_np = torch.from_numpy(np_array)
print(tensor_from_np)

tensor([1., 2., 3.], dtype=torch.float64)


# CONVIRTIENDO DE PYTORCH A NUMPY

In [13]:
np_from_tensor = tensor_from_np.numpy()
print(np_from_tensor)

[1. 2. 3.]


## 🔍 Diferencias entre NumPy y PyTorch

| Característica | NumPy (`ndarray`) | PyTorch (`Tensor`) |
|--------------|------------------|-------------------|
| Tipo de dato principal | `numpy.ndarray` | `torch.Tensor` |
| Operaciones matemáticas | ✅ Sí | ✅ Sí |
| Autograd (gradientes) | ❌ No | ✅ Sí |
| Backpropagation | ❌ No | ✅ Sí |
| Uso de GPU | ❌ No | ✅ Sí (`cuda`) |
| Deep Learning | ❌ No | ✅ Sí |
| Redes neuronales | ❌ No | ✅ Sí |
| Compatibilidad con CPU | ✅ Sí | ✅ Sí |
| Compatibilidad con GPU | ❌ No | ✅ Sí |
| Librerías asociadas | SciPy, Pandas | torch.nn, torch.optim |
| Conversión entre formatos | — | Compatible con NumPy |
| Uso principal | Cálculo numérico y análisis de datos | Machine Learning y Deep Learning |
| Framework de IA | ❌ No | ✅ Sí |
| Entrenamiento de modelos | ❌ No | ✅ Sí |

---

## 📌 Conclusión

- **NumPy** se usa principalmente para **cálculo numérico y análisis de datos**.
- **PyTorch** está diseñado para **entrenar modelos de Machine Learning y Deep Learning**.
- **PyTorch = NumPy + gradientes + GPU + redes neuronales** 🚀
