# IMPORTAMOS LA LIBRERIA

In [1]:
import numpy as np

# CREAMOS UN NUMPY ARRAY CON DATOS ALEATORIOS

In [4]:
arr = np.random.randint(1,10,(3,2))
arr

array([[6, 8],
       [5, 4],
       [2, 6]])

# MODIFICAMOS LA FORMA DEL ARRAY

In [5]:
arr.reshape(1,6)

array([[6, 8, 5, 4, 2, 6]])

In [6]:
arr2 = np.random.randint(1,20,10)
arr2

array([16,  8, 15, 19, 16,  3,  7, 19,  5,  7])

In [7]:
matriz = arr2.reshape(2,5)
matriz

array([[16,  8, 15, 19, 16],
       [ 3,  7, 19,  5,  7]])

# FUNCIONES COMUNES

In [10]:
maximo = arr.max()
minimo = arr.min()
print(f'maximo : {maximo}')
print(f'minimo : {minimo}')

maximo : 8
minimo : 2


In [13]:
matriz.max(1)

array([19, 19])

In [14]:
matriz.min(0)

array([ 3,  7, 15,  5,  7])

In [15]:
arr.argmax()

np.int64(1)

In [17]:
matriz.argmin(1)

array([1, 0])

In [18]:
arr.sort()
arr

array([[6, 8],
       [4, 5],
       [2, 6]])

# FUNCIONES ESTADISTICAS

In [19]:
np.median(arr)

np.float64(5.5)

In [20]:
np.std(arr)

np.float64(1.863389981249825)

# FILTROS EN NUMPY

In [22]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [23]:
condicion = arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
arr[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [25]:
arr[arr < 5]

array([1, 2, 3, 4], dtype=int8)

In [26]:
arr_copy = arr.copy()
arr_copy[arr_copy > 5] = 99
arr_copy

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)